/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records;


import java.time.LocalDateTime;

import jooq.tables.Collisions;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CollisionsRecord extends UpdatableRecordImpl<CollisionsRecord> implements Record3<Integer, String[], LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.collisions.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.collisions.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.collisions.involved_planes</code>.
     */
    public void setInvolvedPlanes(String[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.collisions.involved_planes</code>.
     */
    public String[] getInvolvedPlanes() {
        return (String[]) get(1);
    }

    /**
     * Setter for <code>public.collisions.time</code>.
     */
    public void setTime(LocalDateTime value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.collisions.time</code>.
     */
    public LocalDateTime getTime() {
        return (LocalDateTime) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<Integer, String[], LocalDateTime> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<Integer, String[], LocalDateTime> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return Collisions.COLLISIONS.ID;
    }

    @Override
    public Field<String[]> field2() {
        return Collisions.COLLISIONS.INVOLVED_PLANES;
    }

    @Override
    public Field<LocalDateTime> field3() {
        return Collisions.COLLISIONS.TIME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public String[] component2() {
        return getInvolvedPlanes();
    }

    @Override
    public LocalDateTime component3() {
        return getTime();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public String[] value2() {
        return getInvolvedPlanes();
    }

    @Override
    public LocalDateTime value3() {
        return getTime();
    }

    @Override
    public CollisionsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public CollisionsRecord value2(String[] value) {
        setInvolvedPlanes(value);
        return this;
    }

    @Override
    public CollisionsRecord value3(LocalDateTime value) {
        setTime(value);
        return this;
    }

    @Override
    public CollisionsRecord values(Integer value1, String[] value2, LocalDateTime value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CollisionsRecord
     */
    public CollisionsRecord() {
        super(Collisions.COLLISIONS);
    }

    /**
     * Create a detached, initialised CollisionsRecord
     */
    public CollisionsRecord(Integer id, String[] involvedPlanes, LocalDateTime time) {
        super(Collisions.COLLISIONS);

        setId(id);
        setInvolvedPlanes(involvedPlanes);
        setTime(time);
        resetChangedOnNotNull();
    }
}
